[package]
name = "tomato"
version = "0.1.0"
edition = "2024"

[features]
default = []
dbus = ["dep:zbus", "dep:smol"]

[dependencies]
zbus = { version = "5.5.0", optional = true }
smol = { version = "2.0.2", optional = true }